"""Add preco_unit to Product

Revision ID: 39b0d817dd35
Revises: 364dbd63f8d7
Create Date: 2025-10-14 00:44:08.695897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b0d817dd35'
down_revision = '364dbd63f8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=400),
               existing_nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.create_unique_constraint(uq_invoice_numero, ['numero']) # type: ignore

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.alter_column('preco_unit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.drop_column('product_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_unit', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.drop_column('preco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.drop_column('preco_unit')

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])
        batch_op.alter_column('preco_unit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('numero',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('endereco',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
