"""empty message

Revision ID: d08ff92a9fa4
Revises: 
Create Date: 2025-10-16 16:49:31.795339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08ff92a9fa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_item')
    op.drop_table('client')
    op.drop_table('invoice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=64), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.Column('total', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('xml', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), nullable=False),
    sa.Column('cpf_cnpj', sa.VARCHAR(length=40), nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=400), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=300), nullable=True),
    sa.Column('quantidade', sa.INTEGER(), nullable=True),
    sa.Column('preco_unit', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
